### PR TITLE
chore: upgrade deps

### PR DESCRIPTION
**Pull request by codebytere**
As in title. Most are quite out of date.

### CODE REVIEW

**Comment by ckerr** [comment]
CI env needs a compatibility bump

> error @octokit/rest@19.0.4: The engine "node" is incompatible with this module. Expected version ">= 14". Got "10.15.3"

**Comment by codebytere** [comment]
@ckerr fixed!

**Comment by ckerr** [comment]
> Error response from daemon: manifest for circleci/node:16.16 not found: manifest unknown: manifest unknown

:dizzy:

**Comment by codebytere** [comment]
urgh tbh this app is simple enough i'd prefer to just use GH actions

**Review by ckerr — APPROVED** [review]

**Pull request merged**
